class base_asm_sequence extends uvm_object;    
`uvm_object_utils_begin(base_asm_sequence)
    `uvm_object_utils_end
    // new - constructor
    function new (string name = "base_asm_sequence");
      super.new(name);
    endfunction : new

    //virtual function seq_gen(csr_config csr_cfg);
    function seq_gen(inst_generator inst_gen);
    string inst;
    if($value$plusargs("inst=%s",inst))begin
    end
        `asm_log(inst_gen.gen_file,"#0. set vtype value\n")
        `asm_log(inst_gen.gen_file,"#1. set data\n")
        `asm_log(inst_gen.gen_file,"#2. config reg - vstart/vl\n")
        `asm_log(inst_gen.gen_file,"#3. test\n")
        `asm_log(inst_gen.gen_file,"#4. check data\n")

        `asm_log(inst_gen.gen_file,".macro normal_vv_process loop_name=loop para_vstart=0 para_avl=0 para_vs_original_val=0  para_vd_original_val=0 para_vd_ideal_val=0\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"li  a1, 0x0 #initial value\n")
        `asm_log(inst_gen.gen_file,"li  a2, 0x40 #loop times\n")
        `asm_log(inst_gen.gen_file,"la  a3, vtype_value_start\n")
        `asm_log(inst_gen.gen_file,"li  a5, 256 #avl\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"\loop_name:\n")
        `asm_log(inst_gen.gen_file,"#1.set loop lmul&sew\n")
        `asm_log(inst_gen.gen_file,"    lbu    a4, 0x0(a3)    \n")
        `asm_log(inst_gen.gen_file,"    vsetvl a6, a5, a4\n")
        `asm_log(inst_gen.gen_file,"    \n")
        `asm_log(inst_gen.gen_file,"#2.set origianl vs(v8) data\n")
        `asm_log(inst_gen.gen_file,"    li s0, \para_vs_original_val\n")
        `asm_log_para(inst_gen.gen_file,"    %s v8, s0\n",inst)
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"#3.set origianl vd(v16) data\n")
        `asm_log(inst_gen.gen_file,"    li s0, \para_vd_original_val\n")
        `asm_log_para(inst_gen.gen_file,"    %s v16, s0\n",inst)
        `asm_log(inst_gen.gen_file,"vtype_value_start:.dword 0x0b0a090803020100\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0x1b1a191813121110\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0x8b8a898883828180\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0x9b9a999893929190\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0x4b4a494843424140\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0x5b5a595853525150\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0xcbcac9c8c3c2c1c0\n")
        `asm_log(inst_gen.gen_file,"                  .dword 0xdbdad9d8d3d2d1d0\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,".text\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"//.macro loop_name,vstart, avl, vs_original_val, vd_origian_val, vd_ideal_val\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_0, 0, 0, 0x0               , 0x5555555555555555, 0x5555555555555555\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_1, 0, 0, 0x5555555555555555, 0xffffffffffffffff, 0xffffffffffffffff\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_2, 0, 0, 0xffffffffffffffff, 0x0               , 0x0\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_3, 0, 256, 0x0               , 0x5555555555555555, 0x0\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_4, 0, 256, 0x5555555555555555, 0xffffffffffffffff, 0x5555555555555555\n")
        `asm_log(inst_gen.gen_file,"normal_vv_process loop_5, 0, 256, 0xffffffffffffffff, 0x0               , 0xffffffffffffffff\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_6, 1, 0, 0x0               , 0x5555555555555555, 0x0\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_7, 1, 0, 0x5555555555555555, 0xffffffffffffffff, 0x5555555555555555\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_8, 1, 0, 0xffffffffffffffff, 0x0               , 0xffffffffffffffff\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"//.macro loop_name,vstart, avl, vs2_original_val,vs1_original_val, vd_origian_val, vd_ideal_val\n")
        `asm_log(inst_gen.gen_file,"#normal_vvv_process loop_6, 0, 256, 0x0               , 0x0               , 0xffffffffffffffff, 0x0\n")
        `asm_log(inst_gen.gen_file,"#normal_vvv_process loop_7, 0, 256, 0x0               , 0xffffffffffffffff, 0x5555555555555555, 0x0\n")
        `asm_log(inst_gen.gen_file,"#normal_vvv_process loop_8, 0, 256, 0x0               , 0xffffffffffffffff, 0x5555555555555555, 0x0\n")
        `asm_log(inst_gen.gen_file,"#normal_vvv_process loop_9, 0, 256, 0xffffffffffffffff, 0x0               , 0x0, 0xffffffffffffffff\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_9,  1, 256, 0x0               , 0x5555555555555555, 0x5555555555555555\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_10, 1, 256, 0x5555555555555555, 0xffffffffffffffff, 0xffffffffffffffff\n")
        `asm_log(inst_gen.gen_file,"//except_process loop_11, 1, 256, 0xffffffffffffffff, 0x0               , 0x0\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"//exception:\n")
        `asm_log(inst_gen.gen_file,"//    csrr s9, mepc\n")
        `asm_log(inst_gen.gen_file,"//    addi s9, s9, 4\n")
        `asm_log(inst_gen.gen_file,"//    csrw mepc, s9\n")
        `asm_log(inst_gen.gen_file,"//    li s8, 1\n")
        `asm_log(inst_gen.gen_file,"//    mret\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,".option pop\n")
        `asm_log(inst_gen.gen_file,"ret\n")
        `asm_log(inst_gen.gen_file,"\n")
        `asm_log(inst_gen.gen_file,"fail:jr x0\n")
    endfunction
endclass
