+incdir+../../core_ref/uvm_tb
+incdir+../../core_ref/uvm_tb/public_typedef_pkg
+incdir+../../core_ref/uvm_tb/csr_lib
+incdir+../../core_ref/uvm_tb/mem_lib
+incdir+../../core_ref/uvm_tb/dsa_mem_lib
+incdir+../../core_ref/uvm_tb/dsa_mmio_lib
+incdir+../../core_ref/uvm_tb/vu_inst_lib
+incdir+../../core_ref/uvm_tb/mu_inst_lib
+incdir+../../core_ref/uvm_tb/dte_inst_lib
+incdir+../../core_ref/uvm_tb/inst_lib
+incdir+../../core_ref/uvm_tb/core_ref
$PWD/../../core_ref/uvm_tb/vu_inst_lib/dpi/vu_math.c
../../core_ref/uvm_tb/public_typedef_pkg/public_typedef_pkg.sv
../../core_ref/uvm_tb/csr_lib/csr_lib_pkg.sv
../../core_ref/uvm_tb/mem_lib/mem_lib_pkg.sv
../../core_ref/uvm_tb/dsa_mem_lib/dsa_mem_lib_pkg.sv
../../core_ref/uvm_tb/dsa_mmio_lib/dsa_mmio_lib_pkg.sv
../../core_ref/uvm_tb/vu_inst_lib/vu_inst_lib_pkg.sv
../../core_ref/uvm_tb/mu_inst_lib/mu_inst_lib_pkg.sv
../../core_ref/uvm_tb/dte_inst_lib/dte_inst_lib_pkg.sv
../../core_ref/uvm_tb/inst_lib/inst_lib_pkg.sv
../../core_ref/uvm_tb/core_ref/core_ref_pkg.sv
