`include "directed/workload/multicore_directed_scenario_seq.sv"
`include "directed/workload/reference_single_task_scenario_seq.sv"
`include "directed/workload/reference_single_core_multi_task_scenario_seq.sv"
`include "directed/workload/reference_multi_core_multi_task_scenario_seq.sv"
`include "directed/rvcore/fetch_exception_directed_scenario_seq.sv"
`include "directed/rvcore/load_to_use_directed_scenario_seq.sv"
`include "directed/rvcore/dsa_custom_directed_scenario_seq.sv"
