typedef enum {ALU, BEU, FPU, LDQ,STQ,LSU, MDU, ROB,VPU} exe_unit_e;
typedef enum {SAFE_INST,FLUSH_INST,LS_INST,BRANCH_INST,EXCEPT_INST}inst_type_e;
typedef enum {
    ADDI,SLTI,SLTIU,XORI,ORI,ANDI,
    SLLI,SRLI,SRAI,ADD,SUB,SLL,SLT,SLTU,XOR,SRL,SRA,OR,AND,ADDIW,SLLIW,
    SRLIW,SRAIW,ADDW,SUBW,SLLW,SRLW,SRAW,LUI,
    AUIPC,

    MUL,MULH,MULHSU,MULHU,DIV,DIVU,REM,REMU,MULW,
    DIVW,DIVUW,REMW,REMUW,

    FMADD_D,FMADD_S,FMSUB_D,FMSUB_S,FNMADD_D,FNMADD_S,
    FNMSUB_D,FNMSUB_S,FADD_D,FADD_S,FSUB_D,FSUB_S,FMUL_D,FMUL_S,
    FEQ_D,FEQ_S,FLT_D,FLT_S,FLE_D,FLE_S,FSGNJ_D,FSGNJ_S,FSGNJN_D,FSGNJN_S,FSGNJX_D,FSGNJX_S,
    FCVT_W_S,FCVT_WU_S,FCVT_S_W,FCVT_S_L,FCVT_L_S,FCVT_LU_S,FCVT_S_LU,FCVT_S_WU,FCVT_S_D,
    FCVT_D_S,FCVT_W_D,FCVT_D_W,FCVT_L_D,FCVT_D_L,FCVT_WU_D,FCVT_D_WU,FCVT_LU_D,FCVT_D_LU,
    FCLASS_D,FCLASS_S,FMV_X_W,FMV_W_X,FMV_X_D,FMV_D_X,FSQRT_D,FSQRT_S,FMAX_D,FMAX_S,FMIN_D,FMIN_S,FDIV_D,FDIV_S,

    JAL,JALR,
    BEQ, 
    BNE,BLT,BGE,BLTU,BGEU,

//  /*not safe
    PREF_I,PREF_R,PREF_W,
    INVALID_PREF_I,INVALID_PREF_R,INVALID_PREF_W,
    LB,LH,LW,LD,LBU,LHU,LWU,
    SB,SH,SW,SD,
    INVALID_LB,INVALID_LH,INVALID_LW,INVALID_LD,INVALID_LBU,INVALID_LHU,INVALID_LWU,
    INVALID_SB,INVALID_SH,INVALID_SW,INVALID_SD,
    ///*
    FENCE,FENCEI,
    //*/
    LR_W,SC_W,LR_D,SC_D,
    INVALID_LR_W,INVALID_SC_W,INVALID_LR_D,INVALID_SC_D,
    AMOSWAP_W,AMOADD_W,AMOXOR_W,
    AMOOR_W,AMOAND_W,AMOMIN_W,
    AMOMAX_W,AMOMINU_W,AMOMAXU_W,
    AMOSWAP_D,AMOADD_D,AMOXOR_D,
    AMOOR_D,AMOAND_D,
    AMOMIN_D,AMOMAX_D,
    AMOMINU_D,AMOMAXU_D,

    INVALID_AMOSWAP_W,INVALID_AMOADD_W,INVALID_AMOXOR_W,
    INVALID_AMOOR_W,INVALID_AMOAND_W,INVALID_AMOMIN_W,
    INVALID_AMOMAX_W,INVALID_AMOMINU_W,INVALID_AMOMAXU_W,
    INVALID_AMOSWAP_D,INVALID_AMOADD_D,INVALID_AMOXOR_D,
    INVALID_AMOOR_D,INVALID_AMOAND_D,
    INVALID_AMOMIN_D,INVALID_AMOMAX_D,
    INVALID_AMOMINU_D,INVALID_AMOMAXU_D,

    FLW,FLD,FSW,FSD,
    INVALID_FLW,INVALID_FLD,INVALID_FSW,INVALID_FSD,
    //CACHE     = 20'b00000000000000101011,// illegal
 /*
    PREF,PREF_I,PREF_R,PREF_W, 
    CBO_INVALID,CBO_CLEAN,
    CBO_FLUSH,CBO_ZERO,CBO_ALLCLEAN,CBO_ALLFLUSH,

    */

    /*not safe
    SFENCE_VMA  ,//illegal
    */

    /* not safe.flush/config seq*/
    CSRRW,CSRRS,CSRRC,CSRRWI,CSRRSI,CSRRCI,
    //*/

    /*illegal now.except inst
    TLBRA,TLBRI,TLBWA,TLBWI,SIMPOINT
    URET,SRET,
    */

   // /*except inst or flush inst or wfi is special inst
    ECALL,EBREAK,SRET,MRET,DRET,WFI,
    //*/ not safe inst add constraint , trans to be safe inst
    MISALIGN_BEQ ,
    MISALIGN_BNE ,
    MISALIGN_BGE ,
    MISALIGN_BLT ,
    MISALIGN_BLTU,
    MISALIGN_BGEU,
    MISALIGN_JAL,
    RI
}inst_e;
typedef enum {
  N_TYPE,R_TYPE, S_TYPE, U_TYPE, J_TYPE, B_TYPE,I_TYPE,
  FP_R_TYPE,FP_SR_TYPE,FP_R4_TYPE,
  VV_TYPE,VX_TYPE,VF_TYPE,VI_TYPE,VS_TYPE,SX_TYPE,VD_TYPE,
  VLS_TYPE,VLS_IDX_TYPE,VLS_VIDX_TYPE
}inst_format_e;
parameter quit_inst_code = 'h40000033;
parameter pass_quit_inst = 'h33;
