+incdir+.
+incdir+public_typedef_pkg
+incdir+csr_lib
+incdir+mem_lib
+incdir+dsa_mem_lib
+incdir+dsa_mmio_lib
+incdir+vu_inst_lib
+incdir+mu_inst_lib
+incdir+dte_inst_lib
+incdir+inst_lib
+incdir+core_ref
public_typedef_pkg/public_typedef_pkg.sv
csr_lib/csr_lib_pkg.sv
mem_lib/mem_lib_pkg.sv
dsa_mem_lib/dsa_mem_lib_pkg.sv
dsa_mmio_lib/dsa_mmio_lib_pkg.sv
vu_inst_lib/vu_inst_lib_pkg.sv
mu_inst_lib/mu_inst_lib_pkg.sv
dte_inst_lib/dte_inst_lib_pkg.sv
inst_lib/inst_lib_pkg.sv
core_ref/core_ref_pkg.sv
