        .clk_i                    (clk_i),

        .dsa_rw_req_vld_o         (dsa_rw_req_vld_o),
        .dsa_rw_req_rdy_i         (dsa_rw_req_rdy_i),
        .dsa_rw_type_o            (dsa_rw_type_o),
        .dsa_rw_addr_o            (dsa_rw_addr_o),
        .dsa_wr_data_o            (dsa_wr_data_o),
        .dsa_sid_o                (dsa_sid_o),
        .dsa_uid_o                (dsa_uid_o),
        .dsa_tid_o                (dsa_tid_o),
        .dsa_rd_rsp_i             (dsa_rd_rsp_i),
        .dsa_rd_data_i            (dsa_rd_data_i),

        .sm_rw_req_vld_o          (sm_rw_req_vld_o),
        .sm_rw_req_rdy_i          (sm_rw_req_rdy_i),
        .sm_rw_type_o             (sm_rw_type_o),
        .sm_rw_addr_o             (sm_rw_addr_o),
        .sm_wr_data_o             (sm_wr_data_o),
        .sm_amo_type_o            (sm_amo_type_o),
        .sm_wr_byte_en_o          (sm_wr_byte_en_o),
        .sm_rw_id_o               (sm_rw_id_o),
        .sm_rw_rsp_vld_i          (sm_rw_rsp_vld_i),
        .sm_rsp_id_i              (sm_rsp_id_i),
        .sm_rw_rsp_rdy_o          (sm_rw_rsp_rdy_o),
        .sm_rd_data_i             (sm_rd_data_i),
        .sm_rd_ecc_err_i          (sm_rd_ecc_err_i),

        .ctrl_noc_rv_paddr_i      (ctrl_noc_rv_paddr_i),
        .ctrl_noc_rv_psel_i       (ctrl_noc_rv_psel_i),
        .ctrl_noc_rv_penable_i    (ctrl_noc_rv_penable_i),
        .ctrl_noc_rv_pwrite_i     (ctrl_noc_rv_pwrite_i),
        .ctrl_noc_rv_pwdata_i     (ctrl_noc_rv_pwdata_i),
        .ctrl_noc_rv_prdata_o     (ctrl_noc_rv_prdata_o),
        .ctrl_noc_rv_pready_o     (ctrl_noc_rv_pready_o),
        .ctrl_noc_rv_pslverr_o    (ctrl_noc_rv_pslverr_o),

        .ctrl_noc_itcm_paddr_i    (ctrl_noc_itcm_paddr_i),
        .ctrl_noc_itcm_psel_i     (ctrl_noc_itcm_psel_i),
        .ctrl_noc_itcm_penable_i  (ctrl_noc_itcm_penable_i),
        .ctrl_noc_itcm_pwrite_i   (ctrl_noc_itcm_pwrite_i),
        .ctrl_noc_itcm_pwdata_i   (ctrl_noc_itcm_pwdata_i),
        .ctrl_noc_itcm_prdata_o   (ctrl_noc_itcm_prdata_o),
        .ctrl_noc_itcm_pready_o   (ctrl_noc_itcm_pready_o),
        .ctrl_noc_itcm_pslverr_o  (ctrl_noc_itcm_pslverr_o),

        .ctrl_noc_dtcm_psel_i     (ctrl_noc_dtcm_psel_i),
        .ctrl_noc_dtcm_penable_i  (ctrl_noc_dtcm_penable_i),
        .ctrl_noc_dtcm_pwrite_i   (ctrl_noc_dtcm_pwrite_i),
        .ctrl_noc_dtcm_paddr_i    (ctrl_noc_dtcm_paddr_i),
        .ctrl_noc_dtcm_pwdata_i   (ctrl_noc_dtcm_pwdata_i),
        .ctrl_noc_dtcm_prdata_o   (ctrl_noc_dtcm_prdata_o),
        .ctrl_noc_dtcm_pready_o   (ctrl_noc_dtcm_pready_o),
        .ctrl_noc_dtcm_pslverr_o  (ctrl_noc_dtcm_pslverr_o)
