#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate UVC / individual UVM template files from VERIFY_TOOL_PATH templates."""

from __future__ import print_function

import argparse
import os
import re
import shutil
import sys
import time


def die(msg):
    sys.stderr.write(msg + "\n")
    sys.exit(1)


def prompt(msg):
    sys.stdout.write(msg)
    sys.stdout.flush()
    return sys.stdin.readline().rstrip("\n")


# Preset component aliases for simulation environment batch generation.
SIM_ENV_ALIASES = {
    "ref": "ref",
    "case_cfg": "case_cfg",
    "case_config": "case_cfg",
    "vsqr": "vsqr",
    "vsequencer": "vsqr",
    "env": "env",
    "environment": "env",
    "vseq": "vseq",
    "env_pkg": "env_pkg",
    "tc_pkg": "tc_pkg",
    "tb_top": "tb_top",
}


class TbGen(object):
    def __init__(self):
        tool_path = os.environ.get("VERIFY_TOOL_PATH")
        if not tool_path:
            die("[python] Environment variable VERIFY_TOOL_PATH is not set.")

        template_dir = os.path.join(tool_path, "template")
        src_tb_dir = os.path.join(template_dir, "tb")
        src_tc_dir = os.path.join(template_dir, "tc")
        src_spc_dir = os.path.join(template_dir, "special")
        src_bch_dir = os.path.join(template_dir, "bench")

        self.src_ref_abs = {
            "_ref.sv": os.path.join(src_tb_dir, "ref.sv"),
        }
        self.src_tb_abs = {
            "_agent.sv": os.path.join(src_tb_dir, "agent.sv"),
            "_driver.sv": os.path.join(src_tb_dir, "driver.sv"),
            "_monitor.sv": os.path.join(src_tb_dir, "monitor.sv"),
            "_sequencer.sv": os.path.join(src_tb_dir, "sequencer.sv"),
            "_seq_item.sv": os.path.join(src_tb_dir, "seq_item.sv"),
            "_base_sequence.sv": os.path.join(src_tb_dir, "base_sequence.sv"),
            "_if.sv": os.path.join(src_tb_dir, "if.sv"),
            "_config.sv": os.path.join(src_tb_dir, "config.sv"),
            "_sequence.sv": os.path.join(src_tb_dir, "sequence.sv"),
            "_pkg.sv": os.path.join(src_tb_dir, "tb_pkg.sv"),
        }
        self.src_spc_abs = {
            "_env_config.sv": os.path.join(src_spc_dir, "env_config.sv"),
            "_case_config.sv": os.path.join(src_spc_dir, "case_config.sv"),
            "_env_pkg.sv": os.path.join(src_spc_dir, "env_pkg.sv"),
            "_environment.sv": os.path.join(src_spc_dir, "environment.sv"),
            "_reset_if.sv": os.path.join(src_spc_dir, "reset_if.sv"),
            "_reset_monitor.sv": os.path.join(src_spc_dir, "reset_monitor.sv"),
            "_reset_sequence.sv": os.path.join(src_spc_dir, "reset_sequence.sv"),
            "_scoreboard.sv": os.path.join(src_spc_dir, "scoreboard.sv"),
            "_vsequencer.sv": os.path.join(src_spc_dir, "vsequencer.sv"),
            "_base_vsequence.sv": os.path.join(src_spc_dir, "base_sequence.sv"),
            "_override_vsequence.sv": os.path.join(
                src_spc_dir, "override_vsequence.sv"
            ),
            "_vsequence.sv": os.path.join(src_spc_dir, "vsequence.sv"),
        }
        self.src_tc_abs = {
            "_base_test.sv": os.path.join(src_tc_dir, "base_test.sv"),
            "_test.sv": os.path.join(src_tc_dir, "test.sv"),
            "_tc_pkg.sv": os.path.join(src_tc_dir, "tc_pkg.sv"),
        }
        self.src_bch_abs = {
            "_tb_top.sv": os.path.join(src_bch_dir, "tb_top.sv"),
        }

        self.comp_map = {
            "0": ("_ref", "ref"),
            "1": ("_agent", "tb"),
            "2": ("_driver", "tb"),
            "3": ("_monitor", "tb"),
            "4": ("_sequencer", "tb"),
            "5": ("_seq_item", "tb"),
            "6": ("_base_sequence", "tb"),
            "7": ("_if", "tb"),
            "8": ("_config", "tb"),
            "9": ("_sequence", "tb"),
            "10": ("_pkg", "tb"),
            "11": ("_env_config", "spc"),
            "12": ("_environment", "spc"),
            "13": ("_reset_if", "spc"),
            "14": ("_reset_monitor", "spc"),
            "15": ("_reset_sequence", "spc"),
            "16": ("_scoreboard", "spc"),
            "17": ("_vsequencer", "spc"),
            "18": ("_base_vsequence", "spc"),
            "19": ("_override_vsequence", "spc"),
            "20": ("_vsequence", "spc"),
            "21": ("_base_test", "tc"),
            "22": ("_test", "tc"),
            "23": ("_tc_pkg", "tc"),
            "24": ("_tb_top", "bch"),
            "25": ("_case_config", "spc"),
            "26": ("_env_pkg", "spc"),
        }

        self.sim_env_default_components = [
            "ref",
            "case_cfg",
            "vsqr",
            "env",
            "vseq",
            "env_pkg",
            "tc_pkg",
            "tb_top",
        ]

    def mode_select(self):
        print("1)Enter 1 to Create A UVC Enviroment")
        print("2)Enter 2 to Generate Individual Template")
        print("3)Enter 3 to Generate Simulation Env Templates (batch)")
        mode_sel = prompt("Select [1-3]:")

        if mode_sel == "1":
            self.generate_tb(mode_sel)
        elif mode_sel == "2":
            print("0)  Ref")
            print("1)  Agent")
            print("2)  Driver")
            print("3)  Monitor")
            print("4)  Sequencer")
            print("5)  Sequence item")
            print("6)  Base sequence")
            print("7)  Interface")
            print("8)  Agent config")
            print("9)  Sequence extend from base_seq")
            print("10) Tb package")
            print("11) Environment config")
            print("12) Environment class")
            print("13) Reset interface")
            print("14) Reset monitor")
            print("15) Reset sequence")
            print("16) Scoreboard")
            print("17) Vsequencer")
            print("18) Base_vsequence")
            print("19) Override_vsequence")
            print("20) Vsequence")
            print("21) Base test")
            print("22) Test")
            print("23) Tc package")
            print("24) Tb top ")
            print("25) Case config")
            print("26) Env pkg")
            comp_sel = prompt("Select[0-26]:")
            if comp_sel in self.comp_map:
                suffix, _group = self.comp_map[comp_sel]
                self.generate_tb(mode_sel, comp_sel, suffix)
        elif mode_sel == "3":
            class_name = prompt("Enter A Class Name:\n")
            user_name = prompt("Enter User Name:\n")
            tb_dir = prompt("Enter TB directory [uvm_tb]:\n") or "uvm_tb"
            tc_dir = prompt("Enter TC directory [uvm_tc]:\n") or "uvm_tc"
            bench_dir = prompt("Enter Bench directory [bench]:\n") or "bench"
            self.generate_sim_env(
                class_name, user_name, tb_dir, tc_dir, bench_dir=bench_dir
            )

    def generate_tb(self, mode_sel, comp_sel=None, string=None):
        mode_sel = int(mode_sel)

        if mode_sel == 1:
            uvc_name = prompt("Enter A UVC Name:\n")
            user_name = prompt("Enter User Name:\n")

            uvc_dir = "{}_uvc".format(uvc_name)
            try:
                os.mkdir(uvc_dir, 0o755)
            except OSError as exc:
                die(
                    "[python]Cannot make '{}' directory:{}".format(
                        uvc_dir, exc
                    )
                )
            os.chdir(uvc_dir)

            for suffix, src_abs in self.src_tb_abs.items():
                dst_abs = "{}{}".format(uvc_name, suffix)
                self.replace_pattern(src_abs, dst_abs, uvc_name, user_name)

            seq_dir = os.path.join(os.getcwd(), "seq")
            try:
                os.mkdir(seq_dir, 0o755)
            except OSError as exc:
                die(
                    "[python]Cannot make '{}' directory:{}".format(
                        seq_dir, exc
                    )
                )
            shutil.move("{}_base_sequence.sv".format(uvc_name), seq_dir + "/")
            shutil.move("{}_sequence.sv".format(uvc_name), seq_dir + "/")

        elif mode_sel == 2:
            uvc_name = prompt("Enter A Class Name:\n")
            user_name = prompt("Enter User Name:\n")
            print("{},{}".format(comp_sel, string))

            comp_sel = int(comp_sel)
            if comp_sel == 0:
                self._gen_from_map(
                    self.src_ref_abs, string, uvc_name, user_name, "ref"
                )
            elif 1 <= comp_sel <= 10:
                self._gen_from_map(
                    self.src_tb_abs, string, uvc_name, user_name, "tb"
                )
            elif comp_sel in (11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26):
                self._gen_from_map(
                    self.src_spc_abs, string, uvc_name, user_name, "spc"
                )
            elif comp_sel in (21, 22, 23):
                self._gen_from_map(
                    self.src_tc_abs, string, uvc_name, user_name, "tc"
                )
            elif comp_sel == 24:
                self._gen_from_map(
                    self.src_bch_abs, string, uvc_name, user_name, "bch"
                )

    def _normalize_components(self, components):
        if not components:
            return list(self.sim_env_default_components)

        normalized = []
        for item in components:
            alias = SIM_ENV_ALIASES.get(item.strip().lower())
            if not alias:
                die(
                    "[python] Unknown component '{}'. "
                    "Valid: {}".format(
                        item,
                        ", ".join(sorted(set(SIM_ENV_ALIASES.values()))),
                    )
                )
            if alias not in normalized:
                normalized.append(alias)
        return normalized

    def _ensure_dir(self, path):
        if not os.path.isdir(path):
            try:
                os.makedirs(path)
            except OSError as exc:
                die(
                    "[python]Cannot make '{}' directory:{}".format(
                        path, exc
                    )
                )

    def generate_sim_env(
        self,
        class_name,
        user_name,
        tb_dir="uvm_tb",
        tc_dir="uvm_tc",
        bench_dir="bench",
        components=None,
    ):
        """Batch-generate simulation env templates into build layout."""
        selected = self._normalize_components(components)
        generated = []

        file_plan = []
        if "ref" in selected:
            file_plan.append(
                (
                    self.src_ref_abs["_ref.sv"],
                    os.path.join(tb_dir, "ref", "{}_ref.sv".format(class_name)),
                )
            )
        if "case_cfg" in selected:
            file_plan.append(
                (
                    self.src_spc_abs["_case_config.sv"],
                    os.path.join(tb_dir, "{}_case_config.sv".format(class_name)),
                )
            )
        if "vsqr" in selected:
            file_plan.append(
                (
                    self.src_spc_abs["_vsequencer.sv"],
                    os.path.join(tb_dir, "{}_vsequencer.sv".format(class_name)),
                )
            )
        if "env" in selected:
            file_plan.append(
                (
                    self.src_spc_abs["_environment.sv"],
                    os.path.join(tb_dir, "{}_environment.sv".format(class_name)),
                )
            )
        if "vseq" in selected:
            file_plan.extend(
                [
                    (
                        self.src_spc_abs["_base_vsequence.sv"],
                        os.path.join(
                            tb_dir,
                            "vseq",
                            "{}_base_vsequence.sv".format(class_name),
                        ),
                    ),
                    (
                        self.src_spc_abs["_vsequence.sv"],
                        os.path.join(
                            tb_dir,
                            "vseq",
                            "{}_vsequence.sv".format(class_name),
                        ),
                    ),
                ]
            )
        if "env_pkg" in selected:
            file_plan.append(
                (
                    self.src_spc_abs["_env_pkg.sv"],
                    os.path.join(tb_dir, "{}_env_pkg.sv".format(class_name)),
                )
            )
        if "tc_pkg" in selected:
            file_plan.extend(
                [
                    (
                        self.src_tc_abs["_base_test.sv"],
                        os.path.join(tc_dir, "{}_base_test.sv".format(class_name)),
                    ),
                    (
                        self.src_tc_abs["_test.sv"],
                        os.path.join(tc_dir, "{}_test.sv".format(class_name)),
                    ),
                    (
                        self.src_tc_abs["_tc_pkg.sv"],
                        os.path.join(tc_dir, "{}_tc_pkg.sv".format(class_name)),
                    ),
                ]
            )
        if "tb_top" in selected:
            file_plan.append(
                (
                    self.src_bch_abs["_tb_top.sv"],
                    os.path.join(bench_dir, "{}_tb_top.sv".format(class_name)),
                )
            )

        for src_abs, dst_abs in file_plan:
            self._ensure_dir(os.path.dirname(os.path.abspath(dst_abs)))
            self.replace_pattern(src_abs, dst_abs, class_name, user_name)
            generated.append(dst_abs)

        print(
            "[tbgen] Generated {} file(s) for '{}':".format(
                len(generated), class_name
            )
        )
        for path in generated:
            print("  {}".format(path))
        return generated

    def _gen_from_map(self, src_map, string, uvc_name, user_name, group):
        for key, src_abs in src_map.items():
            matched = False
            if group == "ref":
                matched = bool(
                    re.search(
                        r"(^{0}\.sv)|(^\.{0})".format(re.escape(string)),
                        key,
                        re.I,
                    )
                )
            elif group == "tb":
                matched = bool(
                    re.search(
                        r"(^{0}\.sv)|(^\.{0})".format(re.escape(string)),
                        key,
                        re.I,
                    )
                )
            elif group == "spc":
                matched = bool(
                    re.search(
                        r"^{}\.sv".format(re.escape(string)), key, re.I
                    )
                )
            elif group == "tc":
                matched = bool(
                    re.search(
                        r"{}((\.sv)|(\.pkg))?".format(re.escape(string)),
                        key,
                        re.I,
                    )
                )
            elif group == "bch":
                matched = bool(
                    re.search(
                        r"{}((\.sv)|(\.pkg)|(\.v))?".format(
                            re.escape(string)
                        ),
                        key,
                        re.I,
                    )
                )
            if matched:
                dst_abs = "{}{}".format(uvc_name, key)
                self.replace_pattern(src_abs, dst_abs, uvc_name, user_name)

    def replace_pattern(self, src_file, dst_file, uvc_name, user_name):
        file_name = uvc_name.upper()
        class_name = uvc_name

        try:
            src_fh = open(src_file, "r")
        except IOError:
            die('[python] Missing file: "{}" '.format(src_file))

        try:
            dst_fh = open(dst_file, "w")
        except IOError:
            die('[python] Missing file: "{}" '.format(dst_file))

        for line in src_fh:
            while True:
                m = re.search(r"\$\((\w+)\)", line)
                if not m:
                    break
                token = m.group(1)
                if token == "CLASSNAME":
                    repl = class_name
                elif token == "FILENAME":
                    repl = file_name
                elif token == "USER":
                    repl = user_name
                elif token == "Date":
                    st = time.localtime()
                    repl = "{}-{}-{} {}:{}".format(
                        st.tm_year,
                        st.tm_mon,
                        st.tm_mday,
                        st.tm_hour,
                        st.tm_min,
                    )
                else:
                    break
                line = line[: m.start()] + repl + line[m.end() :]
            dst_fh.write(line)

        src_fh.close()
        dst_fh.close()


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Generate UVM template files from VERIFY_TOOL_PATH templates."
    )
    parser.add_argument(
        "--batch",
        action="store_true",
        help="Non-interactive batch mode (sim env preset by default).",
    )
    parser.add_argument(
        "-n",
        "--name",
        dest="class_name",
        help="Class / project name (required in batch mode).",
    )
    parser.add_argument(
        "-u",
        "--user",
        dest="user_name",
        help="Author name (required in batch mode).",
    )
    parser.add_argument(
        "--tb-dir",
        default="uvm_tb",
        help="Target uvm_tb directory for batch mode [default: uvm_tb].",
    )
    parser.add_argument(
        "--tc-dir",
        default="uvm_tc",
        help="Target uvm_tc directory for batch mode [default: uvm_tc].",
    )
    parser.add_argument(
        "--bench-dir",
        default="bench",
        help="Target bench directory for batch mode [default: bench].",
    )
    parser.add_argument(
        "-c",
        "--components",
        help=(
            "Comma-separated components for batch mode: "
            "ref,case_cfg,vsqr,env,vseq,env_pkg,tc_pkg,tb_top. "
            "Default: all of the above."
        ),
    )
    return parser.parse_args(argv)


def main():
    args = parse_args(sys.argv[1:])
    gen = TbGen()

    if args.batch:
        if not args.class_name or not args.user_name:
            die("[python] Batch mode requires --name and --user.")
        components = None
        if args.components:
            components = [c.strip() for c in args.components.split(",") if c.strip()]
        gen.generate_sim_env(
            args.class_name,
            args.user_name,
            tb_dir=args.tb_dir,
            tc_dir=args.tc_dir,
            bench_dir=args.bench_dir,
            components=components,
        )
    elif len(sys.argv) > 1:
        die(
            "[python] Unknown arguments. Use --batch for non-interactive mode "
            "or run without arguments for interactive mode."
        )
    else:
        gen.mode_select()


if __name__ == "__main__":
    main()
