#!/usr/bin/env python
"""Generate the ordered VCS filelist for the AXI VIP path selected by vip_cfg."""

from __future__ import print_function

import argparse
import json
import os
import posixpath
import sys


DEFAULT_VIP_PATH = "tb/axi4"
PRE_SEQUENCE_FILES = (
    "axi4_if.sv",
    "axi4_irq_if.sv",
    "axi4_vip_adapter_pkg.sv",
    "simple_axi4_bfm_adapter.sv",
    "axi4_interrupt_pkg.sv",
    "axi4_vip_env_pkg.sv",
)
POST_SEQUENCE_FILES = (
    "axi4_doc_test_pkg.sv",
    "axi4_simple_mem_slave.sv",
)


def clean_path(value):
    path = str(value if value is not None else "").strip()
    if not path:
        raise ValueError("axi.vip_path must not be empty")
    if any(char.isspace() for char in path):
        raise ValueError("axi.vip_path must not contain whitespace: %s" % path)
    return path


def resolve_vip_path(path, project_root):
    expanded = os.path.expanduser(os.path.expandvars(path))
    if "$" in expanded:
        raise ValueError("axi.vip_path contains an undefined environment variable: %s" % path)
    resolved = expanded if os.path.isabs(expanded) else os.path.join(project_root, expanded)
    resolved = os.path.abspath(resolved)
    if not os.path.isdir(resolved):
        raise ValueError("axi.vip_path directory does not exist: %s" % path)
    return expanded.replace(os.sep, "/"), resolved


def require_sources(display_path, resolved_path):
    missing = []
    for filename in PRE_SEQUENCE_FILES + POST_SEQUENCE_FILES:
        if not os.path.isfile(os.path.join(resolved_path, filename)):
            missing.append(filename)
    if missing:
        raise ValueError(
            "axi.vip_path %s is missing required compatible adapter files: %s"
            % (display_path, ", ".join(missing))
        )


def source_path(vip_path, filename):
    return posixpath.join(vip_path.rstrip("/"), filename)


def generate(cfg, project_root):
    axi = cfg.get("axi", {})
    if not isinstance(axi, dict):
        raise ValueError("axi configuration must be an object")
    configured_path = clean_path(axi.get("vip_path", DEFAULT_VIP_PATH))
    vip_path, resolved_path = resolve_vip_path(configured_path, project_root)
    require_sources(configured_path, resolved_path)

    lines = [
        "# Auto-generated by scripts/gen_axi_vip_filelist.py. Do not edit by hand.",
        "+incdir+tb",
        "+incdir+%s" % vip_path,
        "+incdir+tb/generated",
        "+incdir+tb/generated/seqs",
        "tb/generated/axi4_vip_cfg_pkg.sv",
        "tb/generated/axi4_seq_cfg_pkg.sv",
    ]
    lines.extend(source_path(vip_path, filename) for filename in PRE_SEQUENCE_FILES)
    lines.append("tb/generated/axi4_generated_seq_pkg.sv")
    lines.extend(source_path(vip_path, filename) for filename in POST_SEQUENCE_FILES)
    lines.append("tb/tb_top.sv")
    return configured_path, lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cfg", default="tb/generated/axi4_vip_cfg.json")
    parser.add_argument("--out", default="tb/generated/axi4_vip_filelist.f")
    parser.add_argument("--project-root", default=".")
    args = parser.parse_args()

    with open(args.cfg, "r") as cfg_file:
        cfg = json.load(cfg_file)
    vip_path, lines = generate(cfg, os.path.abspath(args.project_root))

    out_dir = os.path.dirname(args.out)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with open(args.out, "w") as out_file:
        out_file.write("\n".join(lines) + "\n")
    print("Generated %s with axi.vip_path=%s" % (args.out, vip_path))
    return 0


def cli_main():
    try:
        return main()
    except (IOError, OSError, ValueError) as err:
        print("ERROR: %s" % err, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(cli_main())
