#!/usr/bin/env python3
import argparse
import json
import os
import shutil

SUPPORTED_MODES = {"RV_BYPASS", "TS_BYPASS"}
SEND_UNIT = {"dte": "00", "mu": "01", "vu": "10"}

def load_scenes(path):
    with open(path, "r", encoding="utf-8") as handle:
        root = json.load(handle)
    scenes = root.get("scenes")
    if not isinstance(scenes, list) or not scenes:
        raise ValueError("scenes must be a non-empty list")
    ids = set()
    for scene in scenes:
        scene_id = scene["scene_id"]
        if scene_id in ids:
            raise ValueError("duplicate scene_id %s" % scene_id)
        ids.add(scene_id)
        unknown = set(scene["modes"]) - SUPPORTED_MODES - {"FULL"}
        if unknown:
            raise ValueError("unsupported mode(s): %s" % sorted(unknown))
        chain = scene["task_chain"]
        tasks = chain["tasks"]
        if chain["task_num"] != len(tasks):
            raise ValueError("task_num does not match tasks length")
        task_ids = [task["task_id"] for task in tasks]
        if task_ids != list(range(1, len(tasks) + 1)):
            raise ValueError("task_id must be unique and start at 1")
        for task in tasks:
            if task["task_type"] != "normal":
                raise ValueError("only normal task_type is supported")
            if task["execute_unit"] not in SEND_UNIT:
                raise ValueError("invalid execute_unit")
            if task["execution_mode"] not in ("rvcore_only", "rvcore_dsa"):
                raise ValueError("invalid execution_mode")
    return scenes

def resolve_start_pc(task):
    # Smoke fixture resolution point; replace with the real inst_generator call later.
    if task["task_id"] == 1:
        return 0x00001000
    raise ValueError("no smoke start_pc fixture for task_id %s" % task["task_id"])

def write_scene_artifacts(scene, output_root, sim_rtl_root, pre_sim_root):
    scene_dir = os.path.join(output_root, "scene_%03d" % scene["scene_id"])
    stimulus_dir = os.path.join(scene_dir, "stimulus")
    dut_cfg_dir = os.path.join(scene_dir, "dut_cfg")
    program_dir = os.path.join(scene_dir, "program")
    for path in (scene_dir, stimulus_dir, dut_cfg_dir, program_dir):
        os.makedirs(path, exist_ok=True)
    tasks_out, ts_lines, cfg_lines = [], [], []
    tasks = scene["task_chain"]["tasks"]
    for index, task in enumerate(tasks):
        start_pc = resolve_start_pc(task)
        dsa_en = 1 if task["execution_mode"] == "rvcore_dsa" else 0
        recv_unit = "01" if dsa_en else "00"
        task_out = dict(task)
        task_out.update({"uid": 0, "stream_id": 0, "pid": 0, "vcid": 0,
                         "start_pc": "0x%08x" % start_pc})
        tasks_out.append(task_out)
        ts_lines.append("%04x %02x %x %08x %s %s %02x %x" % (
            0, task["task_id"], 0, start_pc, task["execute_unit"].upper(),
            task["execution_mode"].upper(), 0, 0))
        cfg_lines.extend([
            "[task_%d]" % task["task_id"],
            "TASK_PC=0x%08x" % start_pc,
            "TASK_SEND_UNIT=%s" % SEND_UNIT[task["execute_unit"]],
            "TASK_DSA_EN=%d" % dsa_en,
            "TASK_RECV_UNIT=%s" % recv_unit,
            "TASK_END=%d" % (index == len(tasks) - 1)
        ])
    with open(os.path.join(scene_dir, "task_info.json"), "w", encoding="utf-8") as handle:
        json.dump({"scene_id": scene["scene_id"], "tasks": tasks_out}, handle, indent=2)
        handle.write("\n")
    with open(os.path.join(dut_cfg_dir, "ts_cfg.txt"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(cfg_lines) + "\n")
    with open(os.path.join(stimulus_dir, "ts_task.log"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(ts_lines) + "\n")
    req_fixture = os.path.join(sim_rtl_root, "agent_sim", "rv_dsa", "data", "vu_req.log")
    shutil.copyfile(req_fixture, os.path.join(stimulus_dir, "vu_req.log"))
    program_fixture = os.path.join(pre_sim_root, "..", "core_ref", "ref_sim", "src_file", "test.vmem")
    shutil.copyfile(program_fixture, os.path.join(program_dir, "test.vmem"))

def write_case_list(scenes, output_root, rsim_dir):
    lines = ["# Auto-generated by st/pre_sim/generator/scene_generator/generate.py. Do not edit."]
    for scene in scenes:
        sid = scene["scene_id"]
        artifact = "../../../../../pre_sim/output/scene_%03d/stimulus" % sid
        for mode in scene["modes"]:
            if mode == "FULL":
                continue
            name = "scene_%03d_%s" % (sid, mode.lower())
            lines.append("- case_name = %s" % name)
            if mode == "RV_BYPASS":
                lines.extend(["  uvm_tc = rv_dsa_test",
                    "  vcs_tb_args = +CASE_ID=0+REQ_LOG_FILE=%s/vu_req.log+RESP_LATENCY=1" % artifact])
            elif mode == "TS_BYPASS":
                lines.extend(["  uvm_tc = ts_scene_test",
                    "  vcs_tb_args = +TS_SEQ_FILE=%s/ts_task.log" % artifact])
    case_text = "\n".join(lines) + "\n"
    os.makedirs(output_root, exist_ok=True)
    output_case = os.path.join(output_root, "case.lst")
    with open(output_case, "w", encoding="utf-8") as handle:
        handle.write(case_text)
    publish_dir = os.path.join(rsim_dir, "case_lst")
    os.makedirs(publish_dir, exist_ok=True)
    shutil.copyfile(output_case, os.path.join(publish_dir, "case.lst"))

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    pre_sim_root = os.path.abspath(os.path.join(here, "..", ".."))
    parser = argparse.ArgumentParser()
    parser.add_argument("--scene", default=os.path.join(pre_sim_root, "input", "hardware_feature.json"))
    parser.add_argument("--output-dir", default=os.path.join(pre_sim_root, "output"))
    parser.add_argument("--rsim-dir", default=os.path.join(pre_sim_root, "..", "sim_rtl", "agent_sim", "ts", "rsim"))
    args = parser.parse_args()
    scenes = load_scenes(args.scene)
    output_root = os.path.abspath(args.output_dir)
    sim_rtl_root = os.path.abspath(os.path.join(pre_sim_root, "..", "sim_rtl"))
    for scene in scenes:
        write_scene_artifacts(scene, output_root, sim_rtl_root, pre_sim_root)
    write_case_list(scenes, output_root, os.path.abspath(args.rsim_dir))
    print("Generated %d scene(s) and %d runnable case(s)" % (
        len(scenes), sum(len([m for m in scene["modes"] if m != "FULL"]) for scene in scenes)))

if __name__ == "__main__":
    main()
